### ISSUE TITLE
bundletester deps fail in a py35 virtualenv

### ISSUE THREAD

**Issue by ryan-beisner** [juju-solutions/bundletester#106]
```
ubuntu@osci-bastion:/tmp⟫ virtualenv -p python3.5 venv35
Running virtualenv with interpreter /usr/bin/python3.5
Using base prefix '/usr'
New python executable in /tmp/venv35/bin/python3.5
Also creating executable in /tmp/venv35/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.

ubuntu@osci-bastion:/tmp⟫ . venv35/bin/activate

(venv35) ubuntu@osci-bastion:/tmp⟫ pip install bundletester
Collecting bundletester
  Using cached bundletester-0.11.2.tar.gz
Collecting blessings (from bundletester)
  Using cached blessings-1.6.tar.gz
Collecting charm-tools (from bundletester)
  Using cached charm-tools-2.2.0.tar.gz
Collecting coverage (from bundletester)
  Using cached coverage-4.3.4-cp35-cp35m-manylinux1_x86_64.whl
Collecting juju-deployer>=0.6.0 (from bundletester)
  Using cached juju-deployer-0.10.0.tar.gz
Collecting lazr.authentication (from bundletester)
  Using cached lazr.authentication-0.1.3.tar.gz
Collecting mock (from bundletester)
  Using cached mock-2.0.0-py2.py3-none-any.whl
Collecting nose (from bundletester)
  Using cached nose-1.3.7-py3-none-any.whl
Collecting requests<=2.9.1 (from bundletester)
  Using cached requests-2.9.1-py2.py3-none-any.whl
Collecting simplejson>=3.8.0 (from bundletester)
Collecting websocket-client (from bundletester)
  Using cached websocket_client-0.40.0.tar.gz
Collecting juju-wait (from bundletester)
  Using cached juju_wait-2.5.1-py2.py3-none-any.whl
Collecting launchpadlib<1.11 (from charm-tools->bundletester)
  Using cached launchpadlib-1.10.5.tar.gz
Collecting cheetah<=2.4.4 (from charm-tools->bundletester)
  Using cached Cheetah-2.4.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-xui0597r/cheetah/setup.py", line 10, in <module>
        import SetupTools
      File "/tmp/pip-build-xui0597r/cheetah/SetupTools.py", line 50
        except DistutilsPlatformError, x:
                                     ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-xui0597r/cheetah/
(venv35) 1 ubuntu@osci-bastion:/tmp⟫ 
```

**Comment by ghost** [comment]
Running into the same issue here with py35 environment with tox. This is hindering us from moving to python 3.5 environments in our TravisCI environment.
