### ISSUE TITLE
Failing to run tests in bzr branch

### ISSUE THREAD

**Issue by stub42** [juju-solutions/bundletester#12]
For some reason, bundletester seems to care what revision control system I'm using and is unable to run tests on my branch. Possibly this is to do with bzrlib versions, as bundletester needs to be installed in a virtualenv to avoid conflicts between its required version of bzrlib and the system bzrlib. In any case, attempting to sniff and access the VCS seems a waste of time and fraught with danger.

```
stub@belch:~/charms/postgresql/enable-integration-tests$ ~/lib/bundletester/bin/bundletester -t ~/charms/postgresql/enable-integration-tests
Traceback (most recent call last):
  File "/home/stub/lib/bundletester/bin/bundletester", line 9, in <module>
    load_entry_point('bundletester==0.5.0', 'console_scripts', 'bundletester')()
  File "/home/stub/lib/bundletester/local/lib/python2.7/site-packages/bundletester/tester.py", line 77, in main
    suite = spec.SuiteFactory(options, options.testdir)
  File "/home/stub/lib/bundletester/local/lib/python2.7/site-packages/bundletester/spec.py", line 242, in SuiteFactory
    model = classifier(directory)
  File "/home/stub/lib/bundletester/local/lib/python2.7/site-packages/bundletester/spec.py", line 217, in CharmClassifier
    data = lp.infer_charm(directory) or {}
  File "/home/stub/lib/bundletester/local/lib/python2.7/site-packages/bundletester/vcs.py", line 28, in infer_charm
    origin = self.get_origin(directory)
  File "/home/stub/lib/bundletester/local/lib/python2.7/site-packages/bundletester/vcs.py", line 12, in get_origin
    b = branch.Branch.open(directory)
  File "/home/stub/lib/bundletester/local/lib/python2.7/site-packages/bzrlib/branch.py", line 188, in open
    possible_transports=possible_transports)
  File "/home/stub/lib/bundletester/local/lib/python2.7/site-packages/bzrlib/bzrdir.py", line 1079, in open_branch
    possible_transports=possible_transports)
  File "/home/stub/lib/bundletester/local/lib/python2.7/site-packages/bzrlib/branch.py", line 2028, in open
    found_repository = a_bzrdir.find_repository()
  File "/home/stub/lib/bundletester/local/lib/python2.7/site-packages/bzrlib/bzrdir.py", line 571, in find_repository
    raise errors.NoRepositoryPresent(self)
bzrlib.errors.NoRepositoryPresent: No repository present: "file:///tmp/bundletester-8tXQhZ/enable-integration-tests/"
```

**Comment by stub42** [comment]
This particular traceback seems to be that the branch is being copied to a new location, which breaks the branch as the relative path to the shared repository is no longer valid. bundletester then tries to run bzr commands for some reason, which of course fail.
