### ISSUE TITLE
bundletester depends on stuf to run but stuf not installed.

### ISSUE THREAD

**Issue by manjo-git** [juju-solutions/bundletester#21]
ubuntu@manjoubuntu:~$ bundletester --help
Traceback (most recent call last):
  File "/usr/local/bin/bundletester", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2749, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 444, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 725, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 628, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: stuf>=0.9.16

Please make bundletester depend on stuf.

**Comment by tvansteenburgh** [comment]
I *think* this dep needs to be added to charm-tools setup.py, as bundletester itself does not directly require stuf. Will leave this open for now.
