### ISSUE TITLE
bundletester traceback when environment variables "http_proxy" && "https_proxy" are set. 

### ISSUE THREAD

**Issue by sfeole** [juju-solutions/bundletester#31]
Product version: bundetester 0.5.7

I've started to use bundletester last week,  great product thus far! 
Last week I installed bundletester in a controlled networking environment. All of the lab systems are behind a firewall and usually all of my tools require me to sett proxy flags.  

$export http_proxy=http://my.proxy.server:3128
$export https_proxy=http://my.proxy.server:3128

From here i'm able to usually talk with most of the :80/:443 web servers out there and pull urls. 

I found that when I set this using bundletester I see a traceback.   See my output below, I have pasted both results without and with a proxy set in the env.  

Without http_proxy && https_proxy

DEBUG:bundletester.utils:Updating JUJU_ENV: "" -> "maas"
DEBUG:root:Bootstrap environment: maas
DEBUG:deployer.env:Connecting to environment...
DEBUG:deployer.env:Connected to environment
DEBUG:deployer.env: Terminating machines forcefully
DEBUG:root:Waiting for services to be removed...
DEBUG:runner:call ['/usr/local/bin/charm-proof'] (cwd: /tmp/bundletester-epkY2z/mysql)
DEBUG:runner:I: config.yaml: option key has no default value
DEBUG:runner:I: config.yaml: option source has no default value
DEBUG:runner:Exit Code: 0
mysql
    charm-proof                                                            PASS
DEBUG:deployer.env: Terminating machines forcefully
DEBUG:root:Waiting for services to be removed...
DEBUG:runner:call ['/usr/bin/make', '-s', 'lint'] (cwd: /tmp/bundletester-epkY2z/mysql)
DEBUG:runner:New python executable in .venv/bin/python
DEBUG:runner:Installing setuptools, pip, wheel...done.
DEBUG:runner:Collecting flake8
DEBUG:runner:  Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x2b356ebaa2d0>, 'Connection to pypi.python.org timed out. (connect timeout=15)')': /simple/flake8/
DEBUG:runner:  Retrying (Retry(total=3, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x2b356ebc8510>, 'Connection to pypi.python.org timed out. (connect timeout=15)')': /simple/flake8/
DEBUG:runner:  Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x2b356ebc8650>, 'Connection to pypi.python.org timed out. (connect timeout=15)')': /simple/flake8/
DEBUG:runner:  Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x2b356ebc8790>, 'Connection to pypi.python.org timed out. (connect timeout=15)')': /simple/flake8/
DEBUG:runner:  Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x2b356ebc88d0>, 'Connection to pypi.python.org timed out. (connect timeout=15)')': /simple/flake8/

with http_proxy && https_proxy set:

DEBUG:bundletester.utils:Updating JUJU_ENV: "" -> "maas"
DEBUG:root:Bootstrap environment: maas
DEBUG:deployer.env:Connecting to environment...
DEBUG:root:Connecting proxy...
DEBUG:bundletester.utils:Updating JUJU_ENV: "maas" -> ""
Traceback (most recent call last):
  File "/usr/local/bin/bundletester", line 9, in <module>
    load_entry_point('bundletester==0.5.7', 'console_scripts', 'bundletester')()
  File "/usr/local/lib/python2.7/dist-packages/bundletester/tester.py", line 105, in main
    [report.emit(result) for result in run()]
  File "/usr/local/lib/python2.7/dist-packages/bundletester/runner.py", line 133, in __call__
    bootstrapped = self.builder.bootstrap()
  File "/usr/local/lib/python2.7/dist-packages/bundletester/builder.py", line 40, in bootstrap
    self.environment.connect()
  File "/usr/local/lib/python2.7/dist-packages/deployer/env/go.py", line 65, in connect
    self.client = EnvironmentClient.connect(self.name)
  File "/usr/local/lib/python2.7/dist-packages/jujuclient.py", line 460, in connect
    return Connector().run(cls, env_name)
  File "/usr/local/lib/python2.7/dist-packages/jujuclient.py", line 142, in run
    cert_path, data.get('environ-uuid'))
  File "/usr/local/lib/python2.7/dist-packages/jujuclient.py", line 150, in connect_env
    env = cls(endpoint, name=name, ca_cert=cert_path, env_uuid=env_uuid)
  File "/usr/local/lib/python2.7/dist-packages/jujuclient.py", line 448, in __init__
    self.conn = Connector.connect_socket(endpoint, self._ca_cert)
  File "/usr/local/lib/python2.7/dist-packages/jujuclient.py", line 162, in connect_socket
    endpoint, origin=endpoint, sslopt=sslopt)
  File "/usr/local/lib/python2.7/dist-packages/websocket/_core.py", line 104, in create_connection
    websock.connect(url, **options)
  File "/usr/local/lib/python2.7/dist-packages/websocket/_core.py", line 266, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options))
  File "/usr/local/lib/python2.7/dist-packages/websocket/_http.py", line 65, in connect
    sock = _tunnel(sock, hostname, port, auth)
  File "/usr/local/lib/python2.7/dist-packages/websocket/_http.py", line 186, in _tunnel
    "failed CONNECT via proxy status: %r" + status)
TypeError: cannot concatenate 'str' and 'int' objects

-----------------------------

$ pip list
amulet (1.12.0)
argparse (1.2.1)
Babel (1.3)
backports.ssl-match-hostname (3.4.0.2)
blessings (1.6)
boto (2.20.1)
bundletester (0.5.7)

---------------------------------------

**Comment by sfeole** [comment]
I apologize I forgot to update this bug,  after looking through the code, i realized if I had placed a correlating "no_proxy" variable in addition to "http_proxy" && "https_proxy"   That I could avoid this issue entirely which is what I did. in the "no_proxy" clause, i added all local ipv4 addresses, used to communicate with this network and maas server. 

I'm only setting the proxy for http "80" web traffic, I would like all other intranet traffic to communicate outside of the proxy.   Although it's up to you guys if you want this to remain a bug or not.
