### ISSUE TITLE
sudo required to run priviledged commands

### ISSUE THREAD

**Issue by AdamIsrael** [juju-solutions/bundletester#4]
Bundletester currently runs as a non-root user, which can cause some tests to fail (such as while calling apt-get to install a test dependency).

The workaround is to modify test scripts to use sudo, which will work passwordless in the automated test environment, until containerization is done and bundletester can run as root.

**Comment by jhobbs** [comment]
I don't want bundletester to run as root. Why should it need to run as root? I want to run it as 'jenkins' user in an automated test environment. It's currently prompting me for sudo to add a PPA key every time I run it.

**Comment by tvansteenburgh** [comment]
It should only sudo if you use the `sources`, `packages`, or `python_packages` keys in your `tests.yaml`, and it does so in order to `add-apt-repository`, `apt update`, `apt install`, or `pip install`. To avoid this you could install all needed packages before running bundletester.

**Comment by nunofsantos** [comment]
I'm running into the same issue, and it's invoking sudo even when none of those keys are specified in tests.yaml:

```bash
jenkins@nuno:~/bundletest-tempest$ cat tests/tests.yaml 
bootstrap: false
reset: false
tests: "tempest_*"
virtualenv: false
jenkins@nuno:~/bundletest-tempest$ bundletester -v -F -l DEBUG -e maas --no-destroy -r json
DEBUG:deployer.charm:Cache dir /var/lib/jenkins/.juju/.deployer-store-cache/cs_trusty_keystone-255
DEBUG:deployer.charm:Cache dir /var/lib/jenkins/.juju/.deployer-store-cache/cs_~jason-hobbs_trusty_tempest-0
DEBUG:bundletester.utils:Updating JUJU_ENV: "" -> "maas"
[sudo] password for jenkins: 
Sorry, try again.
[sudo] password for jenkins: 
Sorry, try again.
[sudo] password for jenkins: 
Sorry, try again.
sudo: 3 incorrect password attempts
DEBUG:bundletester.utils:Updating JUJU_ENV: "maas" -> ""
Traceback (most recent call last):
  File "/usr/local/bin/bundletester", line 9, in <module>
    load_entry_point('bundletester==0.7.0', 'console_scripts', 'bundletester')()
  File "/var/lib/jenkins/bundletester/bundletester/tester.py", line 149, in entrypoint
    status = main()
  File "/var/lib/jenkins/bundletester/bundletester/tester.py", line 141, in main
    [report.emit(result) for result in run()]
  File "/var/lib/jenkins/bundletester/bundletester/runner.py", line 133, in __call__
    self.build()
  File "/var/lib/jenkins/bundletester/bundletester/runner.py", line 122, in build
    self.builder.add_sources(self.suite.config.sources)
  File "/var/lib/jenkins/bundletester/bundletester/builder.py", line 153, in add_sources
    self.add_source(source)
  File "/var/lib/jenkins/bundletester/bundletester/builder.py", line 149, in add_source
    subprocess.check_call(['sudo', 'apt-add-repository', '--yes', source])
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['sudo', 'apt-add-repository', '--yes', 'ppa:juju/stable']' returned non-zero exit status 1
```

**Comment by tvansteenburgh** [comment]
@nunofsantos Hey, thanks for the traceback, I'll look into fixing that.

**Comment by tvansteenburgh** [comment]
@nunofsantos I think at least one of the charms in your bundle must be setting `sources: ['ppa:juju/stable']`

**Comment by jhobbs** [comment]
Here's the bundle we're using, it doesn't have that.

http://paste.ubuntu.com/17063952/

I also don't see that in the charm itself.

Why would a charm setting "sources: ['ppa:juju/stable']" require sudo
running on the system bundletester is running on?

Jason

**Comment by tvansteenburgh** [comment]
```
tvansteenburgh@xenial-vm:/tmp⟫ charm pull-source cs:precise/keystone-255              
tvansteenburgh@xenial-vm:/tmp⟫ cat /home/tvansteenburgh/src/charms/precise/keystone-255/tests/tests.yaml 
bootstrap: true
reset: false
virtualenv: true
makefile:
    - lint
    - test
sources:
    - ppa:juju/stable
packages:
    - amulet
    - distro-info-data
    - python-ceilometerclient
    - python-cinderclient
    - python-distro-info
    - python-glanceclient
    - python-heatclient
    - python-keystoneclient
    - python-neutronclient
    - python-novaclient
    - python-pika
    - python-swiftclient
```

**Comment by tvansteenburgh** [comment]
The deps are installed and the tests are run on the machine on which bundletester is running.

**Comment by tvansteenburgh** [comment]
FWIW, in our charm CI we bootstrap juju first, then run bundletester inside a docker container so that all the deps/apt repos/other system pollution, etc are confined to that container.

**Comment by jhobbs** [comment]
Ok,

We already have juju installed when we're running this. Shouldn't it avoid
using sudo in that case?

**Comment by jhobbs** [comment]
Actually we don't want to run the keystone tests at all in this case.  Is
there a way to tell bundletester to only run the tests for a single charm,
or to exclude some of the charms in the bundle?

Jason

**Comment by tvansteenburgh** [comment]
@jhobbs Yeah, you can pass `-x <charm name>` (one or more times), or you can use the `excludes` key in tests.yaml (see https://github.com/juju-solutions/bundletester#testsyaml).

**Comment by jhobbs** [comment]
Ok - passing -x keystone and/or adding keystone to the excludes list in
tests.yaml does not stop sudo from running.

(bundletester)jenkins@jason-trusty-dev:~/bundletest-tempest$ bundletester
-v -l DEBUG -e maas --no-destroy -r json -F -x keystone
/var/lib/jenkins/.virtualenvs/bundletester/local/lib/python2.7/site-packages/jujuclient.py:53:
RuntimeWarning: This version of Python does not support TLSv1.2. Please use
Python 2.7.9+ or 3.4+ instead. Attempting to use TLSv1 - may not work with
all versions of Juju.
  'all versions of Juju.', RuntimeWarning)
DEBUG:deployer.charm:Cache dir
/var/lib/jenkins/.juju/.deployer-store-cache/cs_precise_keystone-255
DEBUG:deployer.charm:Cache dir
/var/lib/jenkins/.juju/.deployer-store-cache/cs_~jason-hobbs_trusty_tempest-0
DEBUG:bundletester.utils:Updating JUJU_ENV: "" -> "maas"
sudo: unable to resolve host jason-trusty-dev
[sudo] password for jenkins:


On Mon, Jun 6, 2016 at 8:51 PM, Tim Van Steenburgh <notifications@github.com

**Comment by tvansteenburgh** [comment]
@jhobbs Ok that's a legit bug -- packages are incorrectly being installed for charms that are excluded. I'll get that fixed.

**Comment by tvansteenburgh** [comment]
@jhobbs a035a63ffb89406406cf6eb6a4fe06e237023907 contains a fix for that.

**Comment by jhobbs** [comment]
Great - tested it and it works.  When will it be published to pypi?

**Comment by tvansteenburgh** [comment]
@jhobbs Just published - v0.7.1
