### ISSUE TITLE
No Makefile causes exception with Juju 2.0

### ISSUE THREAD

**Issue by johnsca** [juju-solutions/bundletester#51]
Running bundletester on a bundle (or presumably a charm) that doesn't have a `Makefile` causes the following exception when using Juju 2.0, but not Juju 1.25:

```
[ubuntu@6bd9c0d2db52:~] local.aws:bundle-timeout:- 1 $ bundletester -vF -t bundle:~bigdata-dev/hadoop-processing -b bundle.yaml
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): api.jujucharms.com
Traceback (most recent call last):
  File "/usr/local/bin/bundletester", line 9, in <module>
    load_entry_point('bundletester==0.7.1', 'console_scripts', 'bundletester')()
  File "/usr/local/lib/python2.7/dist-packages/bundletester/tester.py", line 149, in entrypoint
    status = main()
  File "/usr/local/lib/python2.7/dist-packages/bundletester/tester.py", line 129, in main
    suite = spec.SuiteFactory(options, options.testdir)
  File "/usr/local/lib/python2.7/dist-packages/bundletester/spec.py", line 308, in SuiteFactory
    suite.find_suite()
  File "/usr/local/lib/python2.7/dist-packages/bundletester/spec.py", line 177, in find_suite
    self.find_implicit_tests()
  File "/usr/local/lib/python2.7/dist-packages/bundletester/spec.py", line 217, in find_implicit_tests
    suite=self)
  File "/usr/local/lib/python2.7/dist-packages/bundletester/spec.py", line 196, in conditional_make
    stderr=subprocess.STDOUT)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1340, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

A work-around is to add `makefile: []` to `tests.yaml`, but BT should handle this more gracefully by default.  I'm also not sure why it behaves differently in 2.0.

**Comment by tvansteenburgh** [comment]
Is it possible that `make` was not installed?

**Comment by johnsca** [comment]
juju-solutions/charmbox#37

You're right, that does seem to be what caused the error.  Perhaps this issue could just be to report that more gracefully?
