### ISSUE TITLE
bundletester does not know the environment is bootstrapped

### ISSUE THREAD

**Issue by mbruzek** [juju-solutions/bundletester#57]
I am trying to test a bundle with charmbox:devel (2.0-beta15-xenial-amd64) which has the latest version of bundletester installed from tvansteenburgh's ppa. 

### TL;DR
It looks like something broke in beta-15 because this same charmbox was working on beta-14.

```
ubuntu@devbox:~/bundles/bundle-observable-kubernetes$ vi bundle.yaml 
ubuntu@devbox:~/bundles/bundle-observable-kubernetes$ bundletester -F -l DEBUG -v 2>&1 | tee ../../obs_kubes_results.txt                   
DEBUG:deployer.charm:Cache dir /home/ubuntu/.local/share/juju/.deployer-store-cache/cs_filebeat-4
DEBUG:deployer.charm:Cache dir /home/ubuntu/.local/share/juju/.deployer-store-cache/cs_trusty_elasticsearch-16
DEBUG:deployer.charm:Cache dir /home/ubuntu/.local/share/juju/.deployer-store-cache/cs_etcd-0
DEBUG:deployer.charm:Cache dir /home/ubuntu/.local/share/juju/.deployer-store-cache/cs_~containers_kubernetes-8
DEBUG:deployer.charm:Retrieving store charm cs:~containers/kubernetes-8
DEBUG:deployer.charm:Cache dir /home/ubuntu/.local/share/juju/.deployer-store-cache/cs_topbeat-4
DEBUG:deployer.charm:Cache dir /home/ubuntu/.local/share/juju/.deployer-store-cache/cs_trusty_kibana-14
DEBUG:bundletester.utils:Updating JUJU_ENV: "" -> "gce:admin@local/test1"
/usr/local/bin/pip
The directory '/home/ubuntu/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Plea
se check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/ubuntu/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. chec
k the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already up-to-date: amulet in /usr/local/lib/python2.7/dist-packages
Requirement already up-to-date: requests in /usr/local/lib/python2.7/dist-packages (from amulet)
Requirement already up-to-date: libcharmstore in /usr/lib/python2.7/dist-packages (from amulet)
Requirement already up-to-date: PyYAML in /usr/lib/python2.7/dist-packages (from amulet)
Requirement already up-to-date: path.py in /usr/local/lib/python2.7/dist-packages (from amulet)
Requirement already up-to-date: theblues<1.0,>=0.1.1 in /usr/local/lib/python2.7/dist-packages (from libcharmstore->amulet)
Requirement already up-to-date: jujubundlelib>=0.4.1 in /usr/lib/python2.7/dist-packages (from theblues<1.0,>=0.1.1->libcharmstore->amulet)
DEBUG:root:Bootstrap environment: gce:admin@local/test1
DEBUG:deployer.env:Connecting to environment...
error: unrecognized args: ["gce:admin@local/test1"]
DEBUG:bundletester.utils:Updating JUJU_ENV: "gce:admin@local/test1" -> ""
Traceback (most recent call last):
  File "/usr/local/bin/bundletester", line 9, in <module>
    load_entry_point('bundletester==0.8.0', 'console_scripts', 'bundletester')()
  File "/usr/local/lib/python2.7/dist-packages/bundletester/tester.py", line 149, in entrypoint
    status = main()
  File "/usr/local/lib/python2.7/dist-packages/bundletester/tester.py", line 141, in main
    [report.emit(result) for result in run()]
  File "/usr/local/lib/python2.7/dist-packages/bundletester/runner.py", line 134, in __call__
    bootstrapped = self.builder.bootstrap()
  File "/usr/local/lib/python2.7/dist-packages/bundletester/builder.py", line 53, in bootstrap
    self.environment.connect()
  File "/usr/lib/python2.7/dist-packages/deployer/env/go.py", line 88, in connect
    self.client = self.client_class.connect(self.name)
  File "/usr/lib/python2.7/dist-packages/jujuclient/environment.py", line 87, in connect
    return connector().run(cls, env_name)
  File "/usr/lib/python2.7/dist-packages/jujuclient/connector.py", line 41, in run
    jhome, data = self.parse_env(env_name)
  File "/usr/lib/python2.7/dist-packages/jujuclient/juju2/connector.py", line 47, in parse_env
    model = self.get_model(env_name, controller_name, model_name)
  File "/usr/lib/python2.7/dist-packages/jujuclient/juju2/connector.py", line 103, in get_model
    raise EnvironmentNotBootstrapped(env_name)
jujuclient.exc.EnvironmentNotBootstrapped: Environment gce:admin@local/test1 is not bootstrapped
ubuntu@devbox:~/bundles/bundle-observable-kubernetes$ juju status
MODEL  CONTROLLER  CLOUD/REGION        VERSION
test1  gce         google/us-central1  2.0-beta15

APP  VERSION  STATUS  EXPOSED  ORIGIN  CHARM  REV  OS

UNIT  WORKLOAD  AGENT  MACHINE  PUBLIC-ADDRESS  PORTS  MESSAGE

MACHINE  STATE  DNS  INS-ID  SERIES  AZ

ubuntu@devbox:~/bundles/bundle-observable-kubernetes$ juju switch gce
gce:admin@local/test1 (no change)
ubuntu@devbox:~/bundles/bundle-observable-kubernetes$ 
ubuntu@devbox:~/bundles/bundle-observable-kubernetes$ juju version
2.0-beta15-xenial-amd64
```

Please let me know if you need any more information.

**Comment by mbruzek** [comment]
Talking with @tvansteenburgh he indicated the latest python-jujuclient had a fix for this.

I tried updating the latest python-juju client on a running charmbox running on AWS (this time) in this way:
```
bzr branch lp:python-jujuclient 
cd python-jujuclient
sudo pip install -U ./
cd ../bundles/bundle-observable-kubernetes/
bundletester -F -l DEBUG -v 2>&1 | tee ../../obs_kubes_results.txt
```
But got the same error as before, please advise.

**Comment by tvansteenburgh** [comment]
Please paste the output of `juju switch` and 'juju show-model --format yaml`.

**Comment by tvansteenburgh** [comment]
Fixed in python-jujuclient.
