### ISSUE TITLE
Fails against JAAS

### ISSUE THREAD

**Issue by johnsca** [juju-solutions/bundletester#99]
When attempting to run bundletester against JAAS, with a model already created in the cloud (aws, in this case), I got the following error (after packages were installed):

```
Bootstrapping a Juju 2 controller is not supported. Please bootstrap before running bundletester.
```

It seems that BT doesn't properly detect the existing JAAS controller or model in whatever check it does to determine if it needs to bootstrap.

**Comment by kwmonroe** [comment]
I have had success with JAAS/BT by using this syntax:

```
bundletester -Fvl DEBUG -e <jimm>:<model>
```

The controller name is mandatory when you want to run BT against JAAS models.

**Comment by johnsca** [comment]
Actually, being explicit about the env didn't help, but ensuring that my `.go-cookies` file was available got me from the above message to:

```
Traceback (most recent call last):
  File "/usr/local/bin/bundletester", line 9, in <module>
    load_entry_point('bundletester==0.11.2', 'console_scripts', 'bundletester')()
  File "/usr/local/lib/python2.7/dist-packages/bundletester/tester.py", line 163, in entrypoint
    status = main()
  File "/usr/local/lib/python2.7/dist-packages/bundletester/tester.py", line 152, in main
    [report.emit(result) for result in run()]
  File "/usr/local/lib/python2.7/dist-packages/bundletester/runner.py", line 142, in __call__
    bootstrapped = self.builder.bootstrap()
  File "/usr/local/lib/python2.7/dist-packages/bundletester/builder.py", line 57, in bootstrap
    self.environment.connect()
  File "/usr/local/lib/python2.7/dist-packages/deployer/env/go.py", line 78, in connect
    self.client = self.client_class.connect(self.name)
  File "/usr/local/lib/python2.7/dist-packages/jujuclient/environment.py", line 87, in connect
    return connector().run(cls, env_name)
  File "/usr/local/lib/python2.7/dist-packages/jujuclient/connector.py", line 41, in run
    jhome, data = self.parse_env(env_name)
  File "/usr/local/lib/python2.7/dist-packages/jujuclient/juju2/connector.py", line 64, in parse_env
    'password': account['password'],
KeyError: 'password'
```

Though it still seems like it's trying to bootstrap.  I should note that this is running in a lxd container.

**Comment by tvansteenburgh** [comment]
You need a newer jujuclient it looks like. That KeyError was fixed not too long ago.

**Comment by tvansteenburgh** [comment]
Looks like I need to cut a new jujuclient release for pypi. bbiab

**Comment by tvansteenburgh** [comment]
jujuclient-0.54.0 is up on pypi now.

**Comment by johnsca** [comment]
Running in the charmbox Docker container, I get the same `KeyError`.

**Comment by johnsca** [comment]
@tvansteenburgh Thanks.  Testing now.

**Comment by johnsca** [comment]
That got me past the bootstrap issue.
